### ISSUE TITLE
Diagrama de clases Calculadora

### ISSUE THREAD

**Issue by tiznajo** [G5-MP0487-Edix/AE-4.Activities#12]
# Diagrama de clases de Calculadora

## Objeto

Necesitamos realizar el modelado de clases de la Calculadora de la actividad anterior (Actividad 3)

## Especificaciones
N/A

## Criterios de aceptación

Como resultado debe generarse el diagrama de clases en el que se reflejen todas las características del modelo del enunciado de la Actividad 3.

**Comment by tiznajo** [comment]
Este sería un borrador de diagrama de la clase Suma 
![imagen](https://user-images.githubusercontent.com/98710228/158016925-fe227e58-50fb-45e3-adcc-99e8eba7f473.png)

**Comment by mncaseny** [comment]
Están los **Diagramas de clase Calculadora**. Me queda la duda de cómo relacionarlos.

![Uploading diagramas_de_clase_calculadora.png…]()
