### ISSUE TITLE
Diagrama de casos de uso Calculadora

### ISSUE THREAD

**Issue by tiznajo** [G5-MP0487-Edix/AE-4.Activities#13]
# Diagrama de casos de uso Calculadora

## Objeto

Necesitamos disponer de un diagrama en el que aparezcan todos los casos de uso descritos en las clases de Calculadora

## Especificaciones
N/A

## Criterios de aceptación

Como resultado debe generarse el diagrama de casos de uso en el que se reflejen todas las clases del modelo general del enunciado de la Actividad 3

**Comment by tiznajo** [comment]
He creado un boceto de los casos de uso la clase Resta, podemos llevarla a la versión final si no visualizais ninguna mejora.
![imagen](https://user-images.githubusercontent.com/98710228/158017087-87e00d8c-4fff-4a7d-ab74-87954798ec56.png)

**Comment by mncaseny** [comment]
**Casos de uso Calculadora**

<img width="786" alt="casos_de_uso_calculadora" src="https://user-images.githubusercontent.com/81088331/158062307-1ffb4792-fa1c-4845-b07d-1774ce6ffcc1.png">
