### ISSUE TITLE
Gestión de clientes

### ISSUE THREAD

**Issue by aseguragonzalez** [G5-MP0487-Edix/AE-4.Activities#2]
# Mantenimiento de clientes

## Objeto

Necesitamos identificar los casos de uso asociados a las operaciones de gestión o mantenimiento de clientes a partir de los requisitos descritos en el enunciado.

## Requisitos
Se podrán realizar las siguientes operaciones asociadas a clientes:
1. Altas.
2. Bajas.
3. Modificaciones.
4. Consultas .
5. Generación de informes.

## Criterios de aceptación

Como resultado debe generarse el diagrama de casos de uso en el que se reflejen todas las operaciones indicadas en los requisitos.

**Comment by aseguragonzalez** [comment]
Como versión inicial, aunque creo que podemos hacer un análisis mejor
![cu-clientes](https://user-images.githubusercontent.com/2671340/157355612-5b2b09c4-1873-4f46-9d47-411565fcf209.png)

**Comment by tiznajo** [comment]
Tengo dudas con la idea implicita de que una modificación y una baja incluyan la consulta de un cliente pero, el alta no. Descartaría la idea (No tendría que ser necesaría 100% la consulta posterior) o la incluiria en las 3 acciones.

Opción con descarte:
![imagen](https://user-images.githubusercontent.com/98710228/158017329-81c0fac2-c10c-4a04-9db1-554ac1b23ef5.png)

Opción con los 3 elementos:
![imagen](https://user-images.githubusercontent.com/98710228/158017416-1fb8845b-0876-45b4-b1c4-98b50c795534.png)

**Comment by mncaseny** [comment]
Para empezar el diseño, creo que podríamos mejorarlo .
<img width="609" alt="casos_de_uso_cliente" src="https://user-images.githubusercontent.com/81088331/158040523-cab2a304-93a2-4823-b51c-4ad72949bc6e.png">
En cuanto a la lógica a ver qué opináis.
Pienso que excepto en dar de alta al cliente, todos los casos de uso están relacionados con un "include", ya que tanto
para dar de baja, modificar y generar un informe de cliente, previamente se ha de consultar el cliente.

**Comment by aseguragonzalez** [comment]
![image](https://user-images.githubusercontent.com/2671340/158075447-9abecf6e-56d8-4ae8-b999-3e6607abb4de.png)

Hice alguna modificación extra

**Comment by aseguragonzalez** [comment]
La elección de la solución general y la resolución de errores se ha realizado en la Issue global
