### ISSUE TITLE
Gestión de facturas

### ISSUE THREAD

**Issue by aseguragonzalez** [G5-MP0487-Edix/AE-4.Activities#4]
# Gestión del archivo de facturas

## Objeto

Necesitamos identificar los casos de uso asociados a las operaciones de gestión del archivo de facturas a partir de los requisitos descritos en el enunciado.

## Requisitos
Se podrán realizar las siguientes operaciones asociadas a la administración de facturas:
1. Altas.
2. Bajas.
3. Modificaciones.
4. Consultas .
5. Generación de informes.

## Criterios de aceptación

Como resultado debe generarse el diagrama de casos de uso en el que se reflejen todas las operaciones indicadas en los requisitos.

**Comment by aseguragonzalez** [comment]
Pendiente de revisar y sacar más casos de uso, estos son los básicos
![cu-facturas](https://user-images.githubusercontent.com/2671340/157355661-c11d96e9-8509-49ab-a230-1d4d659d9f2a.png)

**Comment by mncaseny** [comment]
<img width="739" alt="gestionar_facturas" src="https://user-images.githubusercontent.com/81088331/158042125-47f8e5a0-be36-406d-b14a-d00d7097dd2c.png">
