### ISSUE TITLE
Modelado de clientes

### ISSUE THREAD

**Issue by aseguragonzalez** [G5-MP0487-Edix/AE-4.Activities#5]
# Modelado de clientes

## Objeto

Necesitamos realizar el modelado de la entidad cliente de acuerdo con las especificaciones del enunciado.

## Especificaciones
El cliente se caracteriza por disponer de la siguiente información:
- Código de cliente
- Nombre 
- Teléfono
- Dirección

Además, cuentan con las siguientes restricciones:
- Un cliente puede tener 1 ó N facturas asociadas.
- Existen dos tipos de clientes:
  1. Empresa, dispone de CIF y razón social.
  2. Particulares, cuentan con un descuento personalizado.

_Si un cliente tiene 0 facturas, entonces no es un cliente, ya que nunca ha comprado._

## Criterios de aceptación

Como resultado debe generarse el diagrama de clases en el que se reflejen todas las características del modelo del enunciado.

**Comment by aseguragonzalez** [comment]
## Clientes

```mermaid
classDiagram

    class Cliente{
        <<abstract>>
    }
    
    class Factura{
        
    }

    Cliente : -int codigoCliente
    Cliente : -String nombre
    Cliente : -String telefono
    Cliente : -String direccion
    Cliente : +getCodigoCliente() int
    Cliente : +setCodigoCliente(int codigo) void
    Cliente : +getNombre() String
    Cliente : +setNombre(String nombre) void
    Cliente : +getTelefono() String
    Cliente : +setTelefono(String telefono) void
    Cliente : +getDireccion() string
    Cliente : +setDireccion(String direccion) void
    Cliente : +getFacturas() Iterator~Factura~
    Cliente : +Cliente()
    Cliente : +Cliente(int codCli, String nombre, String ttlf, String dir)
    Cliente : +Cliente(int codCli, String nombre, String ttlf, String dir, Factura factura)
    Cliente : +agregarFactura(Factura factura) bool
    Cliente : +quitarFactura(Factura factura) bool
    Cliente : +actualizarFactura(Factura factura) bool

    class Empresa
    Empresa : -String cif
    Empresa : -String razonSocial
    Empresa : +getCif() String
    Empresa : +setCif(String cif) void
    Empresa : +getRazonSocial() String
    Empresa : +setRazonSocial(String razonSocial) void
    Empresa : +Empresa()
    Empresa : +Empresa(..., String cif, String razonSocial)
    Empresa : +Empresa(..., Factura factura String cif, String razonSocial)

    class Particular
    Particular : -double descuento
    Particular : +getDescuento() double
    Particular : +setDescuento(double descuento) void
    Particular : +Particular()
    Particular : +Particular(..., double descuento)
    Particular : +Particular(..., Factura factura, double descuento)

    Cliente <|-- Empresa
    Cliente <|-- Particular
    Cliente "1" *-- "1..n" Factura : - facturas

```

_Nota: para facilitar la compresión se han omitido los parámetros del
constructor base._

**Comment by mncaseny** [comment]
Pienso que al tratarse de una relación de generalización (herencia), las flechas tendrían que ir con la punta blanca.

<img width="361" alt="cliente_particular_empresa" src="https://user-images.githubusercontent.com/81088331/158036431-1b6d89cf-39fb-4fb6-ab48-80a21660ecee.png">

**Comment by aseguragonzalez** [comment]
La elección de la solución general y la resolución de errores se ha realizado en la Issue global
