### ISSUE TITLE
Modelado de artículos

### ISSUE THREAD

**Issue by aseguragonzalez** [G5-MP0487-Edix/AE-4.Activities#6]
# Modelado de artículos

## Objeto

Necesitamos realizar el modelado de la entidad artículo de acuerdo con las especificaciones del enunciado.

## Especificaciones
Un artículo se caracteriza por disponer de la siguiente información:
- Código de artículo
- Denominación 
- Precio de venta al público (PVP)
- Stock (cantidad disponible en el almacén)

## Criterios de aceptación

Como resultado debe generarse el diagrama de clases en el que se reflejen todas las características del modelo del enunciado.

**Comment by aseguragonzalez** [comment]
## Artículos

```mermaid
classDiagram
    class Articulo
    Articulo : -int codigoArticulo
    Articulo : -String denominacion
    Articulo : -double pvp
    Articulo : -int stock
    Articulo : +getCodigoArticulo() int
    Articulo : +setCodigoArticulo(int codigo) void
    Articulo : +getDenominacion() String
    Articulo : +setDenominacion(String denominacion) void
    Articulo : +getPvp() double
    Articulo : +setPvp(double pvp) void
    Articulo : +getStock() int
    Articulo : +setStock(int stock) void
    Articulo : +Articulo()
    Articulo : +Articulo(int codigo, String denominacion, double pvp, int stock)
```

**Comment by mncaseny** [comment]
La clase Articulo la he diseñado de la siguiente manera, no he incluido los gets.
<img width="211" alt="clase_articulo" src="https://user-images.githubusercontent.com/81088331/158034409-c89f51fe-f49c-4c3d-94ac-95ddcb999df9.png">

**Comment by aseguragonzalez** [comment]
La elección de la solución general y la resolución de errores se ha realizado en la Issue global
