### ISSUE TITLE
Modelado de facturas

### ISSUE THREAD

**Issue by aseguragonzalez** [G5-MP0487-Edix/AE-4.Activities#7]
# Modelado de facturas

## Objeto

Necesitamos realizar el modelado de la entidad factura de acuerdo con las especificaciones del enunciado.

## Especificaciones
Una factura se caracteriza por disponer de la siguiente información:
- Número de factura
- Fecha de factura

Además, cada factura **está formada por varias líneas de factura (detalles)** donde se refleja:
1. El código de línea (identificador)
2. El código de artículo
3. Las unidades vendidas.
4. El mismo artículo puede estar en muchas líneas de factura.

## Criterios de aceptación

Como resultado debe generarse el diagrama de clases en el que se reflejen todas las características del modelo del enunciado.

**Comment by aseguragonzalez** [comment]
## Facturas

### Opción 1

Representamos el modelo de factura con la misma estructura que utilizaríamos
para almacenar la información en una base de datos

```mermaid
classDiagram

    class LineaFactura
    LineaFactura : -int idLinea
    LineaFactura : -int codigoArticulo
    LineaFactura : -int unidades
    LineaFactura : -double pvp
    LineaFactura : +getIdLinea() int    
    LineaFactura : +getUnidades() int    
    LineaFactura : +getCodigoArticulo() int
    LineaFactura : +getPvp() double
    LineaFactura : LineaFactura()
    LineaFactura : LineaFactura(int idLinea, int codigoArticulo, int unidades)
    LineaFactura : agregarUnidades(int unidades) bool
    LineaFactura : quitarUnidades(int unidades) bool
    LineaFactura : obternerImporte() double

    class Factura
    Factura : -int codigoFactura
    Factura : -LocalDateTime fechaDeFactura    
    Factura : +getCodigoFactura() int
    Factura : +setcodigoFactura(int codigo) void
    Factura : +getFechaDeFactura() LocalDateTime
    Factura : +setFechaDeFactura(LocalDateTime fecha) void
    Factura : +getLineas() Iterator~LineaFactura~
    Factura : +Factura()
    Factura : +Factura(int codigo, LocalDateTime fecha)
    Factura : +agregarArticulo(int codigoArticulo, int unidades) bool
    Factura : +quitarArticulo(int codigoArticulo) bool
    Factura : +agregarUnidades(int codigoArticulo, int unidades) bool
    Factura : +quitarUnidades(int codigoArticulo, int unidades) bool
    Factura : +obtenerImporte() double

    Factura "1" *-- "1..n" LineaFactura : - lineas

```

**Comment by aseguragonzalez** [comment]
### Opción 2

Representamos las facturas mediante la representación de las otras
 entidades del modelo.

```mermaid
classDiagram

    class Articulo

    class LineaFactura
    LineaFactura : -int idLinea    
    LineaFactura : -int unidades    
    LineaFactura : +getIdLinea() int    
    LineaFactura : +getUnidades() int    
    LineaFactura : +getArticulo() Articulo    
    LineaFactura : LineaFactura()
    LineaFactura : LineaFactura(int idLinea, Articulo articulo, int unidades)
    LineaFactura : agregarUnidades(int unidades) bool
    LineaFactura : quitarUnidades(int unidades) bool
    LineaFactura : obternerImporte() double

    class Factura
    Factura : -int codigoFactura
    Factura : -LocalDateTime fechaDeFactura    
    Factura : +getCodigoFactura() int
    Factura : +setcodigoFactura(int codigo) void
    Factura : +getFechaDeFactura() LocalDateTime
    Factura : +setFechaDeFactura(LocalDateTime fecha) void
    Factura : +getLineas() Iterator~LineaFactura~
    Factura : +Factura()
    Factura : +Factura(int codigo, LocalDateTime fecha)
    Factura : +agregarArticulo(Articulo articulo, int unidades) bool
    Factura : +quitarArticulo(Articulo articulo) bool
    Factura : +agregarUnidades(Articulo articulo, int unidades) bool
    Factura : +quitarUnidades(Articulo articulo, int unidades) bool
    Factura : +obtenerImporte() double

    Factura "1" *-- "1..n" LineaFactura : - lineas
    LineaFactura "1" -- "1" Articulo : - articulo

```

**Comment by tiznajo** [comment]
Me parecen muy buenas variaciones, creo que la opción 1 lo simplifica más todo, apostaría por usarla en el trabajo final.

**Comment by mncaseny** [comment]
Dejo aquí el diseño de la relación de composición Factura con Detalle o Línea de factura.
<img width="245" alt="factura_detalle" src="https://user-images.githubusercontent.com/81088331/158034908-f09b6322-fde1-4ef3-ab19-25827144ca2e.png">

**Comment by mncaseny** [comment]
Adjunto el diseño del modelo Artículo con Detalle o línea de Factura y de Factura con Detalle. En mi caso, la flecha con el rombo, la dirijo hacia el Articulo en el caso de la relación de agregación.

<img width="527" alt="articulo_factura_detalle" src="https://user-images.githubusercontent.com/81088331/158035187-94e3cacf-3589-4c7c-8ab3-d09422056be3.png">

**Comment by mncaseny** [comment]
Adjunto el diseño del modelo Artículo con Detalle o línea de Factura y de Factura con Detalle. En mi caso, la flecha con el rombo, la dirijo hacia el Articulo en el caso de la relación de agregación.
<img width="628" alt="articulo_factura_detalle" src="https://user-images.githubusercontent.com/81088331/158035897-a76ebf02-6466-4ca7-aa6f-be9a23292b02.png">

**Comment by mncaseny** [comment]
Adjunto mi diseño en el que en la relación de agregación, la dirección de la flecha con el rombo, la tengo dirigida en diferente posición, al igual que la cardinalidad. Un artículo al poder estar en muchas líneas de factura, le he puesto una cardinalidad de 1..*
<img width="530" alt="articulo_factura_detalle" src="https://user-images.githubusercontent.com/81088331/158036204-1ff26675-fa10-4d54-93f2-bb3dab07ac09.png">

**Comment by aseguragonzalez** [comment]
La elección de la solución general y la resolución de errores se ha realizado en la Issue global
