### ISSUE TITLE
Diagrama global de casos de uso

### ISSUE THREAD

**Issue by aseguragonzalez** [G5-MP0487-Edix/AE-4.Activities#9]
# Diagrama global de casos de uso

## Objeto
Necesitamos disponer de un diagrama en el que aparezcan todos los casos de uso descritos.

## Especificaciones
N/A

## Criterios de aceptación
Como resultado debe generarse el diagrama de casos de uso en el que se reflejen todas las clases del modelo general del enunciado.

**Comment by mncaseny** [comment]
Aquí dejo el **Diagrama Global de Casos de Uso**.
El diseño no me parece demasiado atractivo, podríamos mejorarlo. 
- Lo  he dividido en tres partes, en base a gestionar cada una de las clases **Cliente,** **Articulo** y **Factura.**
- Incluyo los "include" en todos los casos de uso, excepto en dar alta, ya que el resto necesita de otro caso para poder llevarse a cabo la acción.
<img width="870" alt="diagrama_global_de_casos_de_uso" src="https://user-images.githubusercontent.com/81088331/158040227-e6b31290-e8bf-4c96-9074-052c68843c69.png">

**Comment by mncaseny** [comment]
Aquí dejo el **Diagrama Global de Casos de Uso**.
El diseño no me parece demasiado atractivo, podríamos mejorarlo. 
- Lo  he dividido en tres partes, en base a gestionar cada una de las clases **Cliente,** **Articulo** y **Factura.**
- Incluyo los "include" en todos los casos de uso, excepto en dar alta, ya que el resto necesita de otro caso de uso para poder llevar
- 
<img width="830" alt="Captura de pantalla 2022-03-13 a las 18 20 39" src="https://user-images.githubusercontent.com/81088331/158071522-a87f8ec5-4eb8-4bf8-8591-907616895fd4.png">
se a cabo la acción.

**Comment by aseguragonzalez** [comment]
## Gestión de clientes
![image](https://user-images.githubusercontent.com/2671340/158075605-f169804f-74b1-449f-8b14-5eb49fc77ca3.png)

## Gestión de facturas
![image](https://user-images.githubusercontent.com/2671340/158075611-0f9a8c58-b765-4749-8c12-28683f842f43.png)

## Gestion de artículos
![image](https://user-images.githubusercontent.com/2671340/158075653-f928c15f-c07a-4dee-8cfc-74b3dbf7303c.png)

**Comment by mncaseny** [comment]
Hemos discutido soluciones diversas y hemos llegado a una conclusión.
